development: &default
  adapter:  postgresql
  encoding: unicode
  database: db/postgres
  username: <%= ENV.fetch('PG_USER') { 'postgres' }%>
  password: <%= ENV.fetch('PG_PASS') { '' }%>
  pool:     <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host: db

test:
  <<: *default
  database: db/test
